name: py

on:
  push:
  schedule:
    - cron: 00 11 * * *
jobs:
  run-it:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    name: py
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          repository: 'SunYufei/freenom'
      - name: Run
        run: python3 run.py -u '${{ secrets.FREENOM_USERNAME }}' -p '${{ secrets.FREENOM_PASSWORD }}'
